[package]
name = "rusty_gl"
license = "MIT OR Apache-2.0"
description = "Safe thin wrapper for OpenGL using the gl-rs crate"
version = "0.1.0"
authors = ["Matthew Hopson"]

[dependencies]
gl = "0.6.0"